name: Deploy to ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/medusa-backend:latest ./medusa-backend
        docker push ${{ secrets.DOCKER_USERNAME }}/medusa-backend:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: medusa-cluster
        service: medusa-service
        task-definition: your-task-def.json
